### ISSUE TITLE
Set up impsort and formatter plug-in

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/moditect-org-parent#2]
I could swear this was in place already for JfrUnit, but perhaps not? If not, config can be copied from kcctl.

// CC @aalmiray

**Comment by gunnarmorling** [comment]
Applied locally to JfrUnit for now via https://github.com/moditect/jfrunit/issues/76.

**Comment by aalmiray** [comment]
Yeah, those plugins are missing in the parent pom. I'll add them.

**Comment by gunnarmorling** [comment]
Thx! Wanna cut a 1.0.1.Final release of the parent POM with this change?

**Comment by aalmiray** [comment]
I was hoping there could wait for https://github.com/moditect/moditect-org-parent/issues/1 which depends on an external fix.
That being said the current enforcer version in use (`3.0.0-M3`) is working alright.

**Comment by gunnarmorling** [comment]
That makes sense, there's no hurry.
