### ISSUE TITLE
`mvn license:format` fails for JfrUnit

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/moditect-org-parent#3]
Running `mvn license:format` fails for JfrUnit:

```
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.0.rc2:format (default-cli) on project jfrunit: Execution default-cli of goal com.mycila:license-maven-plugin:4.0.rc2:format failed: Cannot read header document ${rootdir}/etc/license.txt. Cause: Resource ${rootdir}/etc/license.txt not found in file system, classpath or URL: no protocol: ${rootdir}/etc/license.txt
```

@aalmiray, any idea about this one?

**Comment by aalmiray** [comment]
Yes, you must run a lifecycle phase that turns on the whistles such as `mvn initialize license:format`. This is due to the bindings created by the parent pom.

**Comment by gunnarmorling** [comment]
Interesting, first time I'm seeing this; and I thought I'd know Maven quite well :) So probably good enough to document it in the README then.

**Comment by aalmiray** [comment]
I think the invocation of an explicit lifecycle phase is needed in this case due to the usage of the `directory` maven plugin that calculates the root of the project.
